### PR TITLE
Add Set overload

### PR DESCRIPTION
**Pull request by Kemsekov**
I had plenty of situations where I needed to set a whole image in one set invoke so I added this method

### CODE REVIEW

**Comment by hazdryx** [comment]
Instead of overriding `Set,` which is typically used with `Color` objects, create a new method called `Write` and include the typical stream parameters like `buffer`, `offset`, and `count`. This is more flexible than just a simple Set.

Also, please document methods and add tests for them, as per the [CONTRIBUTE.md](https://github.com/hazdryx/FastBitmap/blob/master/CONTRIBUTE.md). Something similar would be the `CopyTo` tests.

**Comment by Kemsekov** [comment]
Okey. I'll do as you said.

**Comment by Kemsekov** [comment]
I'll do some fixes and create new commit.

**Comment by hazdryx** [comment]
I made an issue that discusses the new features and a new branch for implementing these so I can approve pull requests quickly without it needing to be official, like in the [CONTRIBUTE.md](https://github.com/hazdryx/FastBitmap/blob/master/CONTRIBUTE.md)

**Pull request closed without merging**
